//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emeci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewMembership
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReferenceBank { get; set; }
        public string PaymentMethod { get; set; }
        public string EMECI { get; set; }
    }
}
